server.port: 8080
base: RUB
changerates:
  api.id: 47435b03e28b4286a1c830c5ce2a1907
  general.url: https://openexchangerates.org/api/
giphy:
  general.url: https://api.giphy.com/v1/gifs/random
  api.id: nUvOIITu7hdlgnEf0wNQKrWyce35XaEQ
  tag:
    rich: rich
    broke: broke
